vlan_names:
  "data_vlan": 1
  "voice_vlan": 2

output_folder:  "output/{{hostname}}"

ansible_host: "{{ managment_ip }}"
ansible_password: password
ansible_user: dhimes
ansible_connection: ansible.netcommon.network_cli


build_order:
  - file: "templates/router_main.j2"
    order: "0000010"
  - file: "templates/acls.j2"
    order: "0000020"
  - file: "templates/{{device_type}}/{{router_switch}}/interfaces.j2"
    order: "0000030"
  - file: "templates/{{device_type}}/aaa.j2"
    order: "0000040"
  - file: "templates/{{device_type}}/l3_data.j2"
    order: "0000050"
  - file: "templates/{{device_type}}/vty.j2"
    order: "0000060"
