---
hostname: R4
managment_ip: 10.0.0.4
managment_snm:  255.255.255.255
need_dfgw: False
eigrp: True
router_switch: router
device_type: ios

ports: 
  interface2: 
    ip_address: 192.168.24.4 255.255.255.0
  interface3: 
    ip_address: 192.168.34.4 255.255.255.0
  interface4: 
    ip_address: 192.168.45.4 255.255.255.0

acl_ssh_looky: False
acl_insecure: False
